load in-domain data:  cifar10_cat
Building CIFAR-10 data loader with 1 workers
==> Building model..

Epoch: 0
Traceback (most recent call last):
  File "/home/home_node4/ssy/BDNN/additional/sdenet/sdenet_mnist.py", line 141, in <module>
    train(epoch)
  File "/home/home_node4/ssy/BDNN/additional/sdenet/sdenet_mnist.py", line 90, in train
    outputs = net(inputs)
  File "/home/home_node4/ssy/anaconda3/envs/BDNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/home_node4/ssy/BDNN/additional/sdenet/models/sdenet_mnist.py", line 141, in forward
    out = self.downsampling_layers(x)
  File "/home/home_node4/ssy/anaconda3/envs/BDNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/home_node4/ssy/anaconda3/envs/BDNN/lib/python3.9/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/home_node4/ssy/anaconda3/envs/BDNN/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/home_node4/ssy/anaconda3/envs/BDNN/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/home_node4/ssy/anaconda3/envs/BDNN/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 32, 32] to have 3 channels, but got 1 channels instead
